import { readFileSync } from 'fs';

/**
 * Convert a file like .txt in a matrix
 * @param path The path of the file to be readed
 * @returns  The matrix generated by the file readed
 */
export function fileToMatrix(path: string) {
  const allFileContent = readFileSync(path, 'utf8').trim();
  const lines = allFileContent.split('\n');
  const cols = lines[0].split(',');
  const matrix: number[][] = []; 
  lines.forEach(_ => matrix.push([]));
  for (let i = 0; i < lines.length; i++) {
    for (let j = 0; j < cols.length; j++) {
      matrix[i][j] = parseInt(lines[i].split(',')[j]);
    }
  }
  return matrix;
}

